version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3002:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000
    restart: unless-stopped
  
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend